name: 'ShutterLab '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff5194'
    - '#191919'
    - '#515151'
    - '#c8c8c8'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
